### ISSUE TITLE
upstream to sanic-org/sanic-ext

### ISSUE THREAD

**Issue by wfleurant** [Relrin/sanic-redis-extension#3]
library should be upstreamed to sanic-org/sanic-ext -- although some things may break with python 3.10 we should start the process for supporting this library. do you have time for this? thanks for creating and sharing this library.

**Comment by Relrin** [comment]
Hey there!

> library should be upstreamed to sanic-org/sanic-ext -- although some things may break with python 3.10 we should start the process for supporting this library. do you have time for this?

Have you tried to use this package against the latest Sanic versions? Does it work properly for you? Are there any issues that faced with?

Since this package relies has only 2 dependencies (which are `sanic-base-extension` and `aioredis`), it still should work properly without any issues.

**Comment by Relrin** [comment]
I have updated & deployed the latest version to PyPI. Feel free to open new pull requests if you run into issues
